## 5A Invariant Subspaces

### Eigenvalues

**Definition 5.1: Operator**
- A linear map from a vector space onto itself is called an *operator*

**Definition 5.2: Invariant Subspace**
- Let $T\in\mathcal{L}(V)$, a subspace $U$ of $V$ is called *invariant* under $T$ if: $$Tu\in U, \ \forall u\in U$$

Consider this operator on $V$. If $T|_U$, which is the mapping of $T$ restricted to the domain of $U$, is an *operator on* $U$, then $U$ is an invariant subspace.

Ex. $T\in\mathcal{L}(\mathcal{P}(\reals))\coloneqq Tp=p'$
- Consider $\mathcal{P}_4(\reals)$. This is a subspace of $\mathcal{P}(\reals)$ that is invariant under $T$ becuase any $p\in\mathcal{P}_4(\reals)$ has degree of at most 4 and its first derivative $p'$ also has degree of at most 4. Thus $p'\in\mathcal{P}_4(\reals)$

Ex. Generically invariant subspaces for any operator $T\in\mathcal{L}(V)$:
- $\{0\}$ is an invariant subspace under $T$: $$Tu=0\in\{0\}, \ \forall u\in\{0\}$$
- $v$ is an invariant subspace under $T$: $$Tu\in V, \ \forall u \in V$$
- $\text{null } T$ is an invariant subspace under $T$: $$Tu=0\in\text{null } T, \ \forall u\in \text{null } T$$
- $\text{range } T$ is an invariant subspace under $T$: $$Tu\in\text{range T}, \ \forall u \in\text{range } T$$

**NOTE:** From these generic examples, it is clear that any operator on $V$ must have at least the invariant subspaces of $\{0\}$ and $V$. However, it turns out (as we will see later) that there must exist more invariant subspaces as well.

**NOTE:** When $T$ is an automorphism (i.e. it is bijective and invertible), then $\text{null }T = \{0\}$ and $\text{range } T = V$

#### Eigenvalues

Consider a one-dimensional subspace. Take any $v\in V$ with $v\ne 0$ and let $U$ be the set of *all scalar multiples* of $v$: $$U=\{\lambda v: \lambda\in\mathbb{F}\} = \text{span}(v)$$
$U$ is a one-dimensional subspace of $V$. Note that $U$ is uniquely defined w.r.t. the chosen $v\in V$. Any one-dimensional subspace of $V$ is similarly defined based on the choice of $v$.\
If $U$ is invariant under an operator $T\in\mathcal{L}(V)$, then $Tv\in U$, and thus there exists a scalar $\lambda\in\mathbb{F}$ such that: $$Tv=\lambda v$$
The converse is also true:\
If $Tv=\lambda v$ for some $\lambda\in\mathbb{F}$, then $\text{span}(v)$ is a one-dimensional subspace of $V$ that is invariant under $T$.

**Definition 5.5: Eigenvalue**
- For $T\in\mathcal{L}(V)$, a number $\lambda \in \mathbb{F}$ is called an *eigenvalue* of $T$ if there exists $v\in V$ such that $v\ne 0$ and $Tv = \lambda v$
- I.e.: $$\exists v\in V : Tv = \lambda v, v\ne 0 \implies \lambda \text{ is eigenvalue}$$

So, $V$ has a one-dimensional subspace that is invariant under $T$ if and only if $T$ has an eigenvalue

Ex. $T\in\mathcal{L}(\mathbb{F}^3)$:
$$ T(x, y, z) = \big(7x + 3z, \ 3x + 6y + 9z, \ -6y \big), \ \forall (x,y,z)\in\mathbb{F}^3$$
Then $T(3, 1, -1) = (18, 6, -6) = 6(3, 1, -1)$, thus $6$ is an *eigenvalue* of $T$

**Equivalent Conditions for an Eigenvalue**
- For finite-dimensional vector space $V$, linear map $T\in\mathcal{L}(V)$, and $\lambda\in\mathbb{F}$:
    - $\lambda \text{ is an eigenvalue of } T$
    - $T - \lambda I \text{ is not injective}$
    - $T - \lambda I \text{ is not surjective}$
    - $T - \lambda I \text{ is not invertible}$

From $Tv = \lambda v$ it follows that $(T - \lambda I)v = 0, \ \forall v \in V$

**Definition 5.8: Eigenvector**
- For $T\in\mathcal{L}(V)$ and eigenvalue $\lambda\in\mathbb{F}$ of $T$, the vector $V\in V$ is called an *eigenvector* of $T$ corresponding to $\lambda$ if $v\ne 0 $ and $Tv = \lambda v$

From the definition of an eigenvalue (5.5), the eigenvalue is specified for a specific vector $v\in V$. This vector is the eigenvector.\
A vector $v\in V$ is an eigenvector of an operator $T$ on $V$ if and only if $Tv$ is a scalar multiple of $v$. Correspondingly, a vector $v\in V$ is an eigenvector of $T$ corresponding to the eigenvalue $\lambda$ if and only if $v\in \text{null}(T - \lambda I)$

**Linear Independence of Eigenvectors**
- For an operator $T\in\mathcal{L}(V)$, *every* list of eigenvectors of $T$ corresponding to distinct eigenvalues of $T$ is linearly independent

*Proof:*

Proof by contradiction. Were this theorem false, then there would exist a linearly dependent list of eigenvectors **of minimal length** $m$, $v_1,...,v_m$ corresponding to *distinct* eigenvalues $\lambda_1,...,\lambda_m$ of $T$. Note that $m\ge 2$ because eigenvectors (and values) are non-zero by definition. Then by the definition of linear dependence, there must exist a set of coefficients $a_1,...,a_m\in\mathbb{F}$, not all zero, such that: $$a_1v_1 + \cdots + a_mv_m = 0$$
Apply $T-\lambda_m I$ to both sides:
$$a_1(\lambda_1 - \lambda_m) v_1 + \cdots + a_{m-1} (\lambda_{m-1} - \lambda_m) v_{m-1} = 0$$
Because the eigenvalues are distinct, none of the coefficients in this equation are 0. Thus the list of eigenvectors $v_1,...,v_{m-1}$ is a linearly dependent list of length $m-1$. This violiates the minimallity of $m$, and thus completes the proof.

Another, I think cleaner proof:\
Apply the operator $T$: $$a_1T(v_1) + \cdots + a_mT(v_m) = 0 \\ \implies a_1\lambda_1 v_1 + \cdots + a_m \lambda_m v_m = 0$$
Because all of the eigenvalues are necessarily distinct, there is no combination of coefficients $a\lambda$ for which this equality holds other than the trivial solution. Thus the eigenvectors must be independent.

**Operators Cannot Have More Eigenvectors than the Dimension of Vector Space**
- For finite-dimensional $V$, each operator on $V$ has *at most* $\dim V$ distinct eigenvalues

This follows clearly from the theorem that eigenvectors are independent. The maximum length of any list of independent vectors in a finite-dimensional vector space $V$ *is* $\dim V$, by the definition of dimension.

### Polynomials Applied to Operators

Operators may be raised to powers. This isn't that remarkable when you think about it. A linear map between subspaces (i.e. between spaces of different dimensions, a non-operator) cannot be composed with itself because the domain will be incompatible after the first mapping. But an operator (i.e. a linear map on the same vector space) may be composed with itself infinitely.

**Notation $T^m$**\
For operator $T\in\mathcal{L}(V)$:
- $T^m\in\mathcal{L}(V)$ is defined by $T^m = T\cdots T$, $m$ times
- $T^0$ is defined to be the identity operator $I$ on $V$
- If $T$ is invertible, then $T^{-m}$ is defined by: $$T^{-m} = (T^{-1})^m$$

**Notation: $p(T)$**\
For operator $T\in\mathcal{L}(V)$ and polynomial $p\in\mathcal{P}(\mathbb{F})$, $p(T)$ is the operator on $V$ defined by: $$p(T) = a_0 I + a_1T + a_2T^2 + \cdots + a_mT^m$$

**Definition 5.16: Product of Polynomials**
- If $p,q \in\mathcal{P}(\mathbb{F})$, then $pq\in\mathcal{P}(\mathbb{F})$ is the polynomial defined by: $$(pq)(z) = p(z)q(z), \ \forall z \in\mathbb{F}$$

**Multiplicative Properties:**
$$\begin{align*}
& a) \ \ (pq)(T) = p(T)q(T) \\
& b) \ \ p(T)q(T) = q(T)p(T)
\end{align*}$$
So, the order doesn't matter. This corresponds exactly with the product of any other polynomials. It is possible because an operator may be composed with itself (so, operators are commutative).

**Null Space and Range of $p(T)$ are invariant under $T$**
- For an operatore $T\in\mathcal{L}(V)$ and a polynomial $p\in\mathcal{P}(\mathbb{F})$, $\text{null } p(T)$ and $\text{range } p(T)$ are both *invariant* under $T$

We saw earlier that the null space and range of an operator are invariant subspaces under the operator. This just extends that logic to the polynomial of an operator, which is intuitive because the polynomial of an operator *is still an operator*.

### Exercises 5A

In [13]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([3, 1, 3, 4, 5])

v = np.column_stack((x, y))

T = np.array([[0, -3], [1, 0]])
print(v)
print(T @ v.T)

[[1 3]
 [2 1]
 [3 3]
 [4 4]
 [5 5]]
[[ -9  -3  -9 -12 -15]
 [  1   2   3   4   5]]


## 5B The Minimal Polynomial

### Existence of Eigenvalues on Complex Vector Spaces

***Major Theorem:***
**Existence of Eigenvalues**
- Every operator on a finite-dimensional nonzero complex vector space has an eigenvalue

*Proof:*\
Let $V$ be a finite-dimensional complex vector space  with dimension $n>0$ and $T\in\mathcal{L}(V)$ be an operator on $V$. Then for some $v\ne 0 \in V$ we may specify polynomials of $T$: $$v, Tv, T^2v, ..., T^n v$$
Note that this is a list of terms of a polynomial $p_n(T)$. Such a list of polynomial *cannot be* linearly independent because its length is $n+1$ and $\dim V = n$. Thus, there exists some non-trivial linear combination of the vectors in this list such that: $$p(T)v = 0$$
The first version of the fundamental theorem of algebra (ch 4) states: "Every non-constant polynomial with complex coefficients has a root in $\mathbb{C}$". Thus, there exists $\lambda \in \mathbb{C} : p(\lambda) = 0$, and some polynomial $q\in\mathcal{P}(\mathbb{C})$ such that: $$p(z) = (z-\lambda)q(z), \ \forall z\in \mathbb{C}$$
Where $p$ has some degree $m$ and $q$ has some degree $m-1$ (ch 4 again)\
This implies that:
$$p(T)v = (T - \lambda I ) \big(q(T)v\big) = 0$$
Because $q$ has degree less than $p$ (i.e. $m-1 < m$), it must be the case that $q(T)v \ne 0$.\
 Thus $\lambda$ is an eigenvalue with eigenvector $q(T)v$

*More Clean Proof:*\
Let $V$ be a complex finite-dimensional vector space with $\dim V = n > 0$ and operator $T\in\mathcal{V}$.\
 Then consider the list of polynomial terms: 
 $$v, Tv, T^2v,...,T^nv, \ v\ne 0 \in V$$
This list *cannot be* linearly independent because it has length $n+1$ while $\dim V = n$.\
 Thus, there exist *complex numbers* $a_0,...,a_n$ not all zero such that: 
 $$a_0v + a_1Tv + a_2T^2v + \cdots + a_n T^n v = 0$$
This equation is a polynomial with complex coefficients.\
 By the fundamental theorem of algebra (ch 4), it has a factorization of the form:
$$a_0 + a_1z + \cdots + a_n z^n = c(z - \lambda_1) \cdots (z - \lambda_m)$$ 
For $c\ne 0 \in \mathbb{C}$ and all $\lambda_j \in \mathbb{C}$\
This factorization is as follows:
$$
\begin{align*}
& 0 = a_0v + a_1Tv + a_2T^2v + \cdots + a_n T^n v \\
& \ \ = \big(a_0 I + a_1 T + \cdots + a_n T^n \big) v \\
& \ \ = c(T - \lambda_1 I ) \cdots (T - \lambda_m I) v
\end{align*}
$$
Because $C \ne 0$ and $v \ne 0$, at least one term $T - \lambda_j I = 0$ in this expression. Equivalently, $T-\lambda_j I$ is *not injective* for some $0<j\le m \le n$ Thus, there exists at least one eigenvalue $\lambda_j$ for $T$.

### Eigenvalues and the Minimal Polynomial

**Definition 5.21: Monic Polynomial**
- A *monic polynomial* is a polynomial whose highest-degree *coefficient* equals $1$
- E.g. $2 + 9z^2 + z^7$ is a monic polynomial of degree $7$

**Existence, Uniqueness, and Degree of the Minimal Polynomial**
- For finite-dimensional $V$ and operator $T\in\mathcal{L}(V)$, there is a unique monic polynomial $p\in\mathcal{p}(\mathbb{F})$ of smallest degree such that:
    - $p(T)=0$
    - $\deg p \le \dim V$